# Generated by Django 3.2.13 on 2022-09-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_remove_class_curriculum_classcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact_no', models.CharField(default='2547xxxxxxxx', max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('subject', models.ManyToManyField(blank=True, to='curriculum.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
