# Generated by Django 4.1.1 on 2022-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentassignment_studentexam_studenttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
