# Generated by Django 4.0.4 on 2022-05-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='c_class',
            new_name='subject_class',
        ),
    ]
