# Generated by Django 4.0.4 on 2022-05-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_rename_c_class_subject_subject_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='curriculum',
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.classcategory'),
            preserve_default=False,
        ),
    ]
