# Generated by Django 3.2.13 on 2022-09-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
        ('curriculum', '0004_assignment_testandquiz_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('marks', models.IntegerField(default=0)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('imageOption1', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption2', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption3', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption4', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('textAnswer', models.CharField(blank=True, choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1, null=True)),
                ('imageAnswer', models.CharField(blank=True, choices=[('A', 'imageOption1'), ('B', 'imageOption2'), ('C', 'imageOption3'), ('D', 'imageOption4')], max_length=1, null=True)),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.testandquiz')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('marks', models.IntegerField(default=0)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('imageOption1', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption2', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption3', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('imageOption4', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('typedAnswer', models.TextField(blank=True, max_length=500, null=True)),
                ('textAnswer', models.CharField(blank=True, choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1, null=True)),
                ('imageAnswer', models.CharField(blank=True, choices=[('A', 'imageOption1'), ('B', 'imageOption2'), ('C', 'imageOption3'), ('D', 'imageOption4')], max_length=1, null=True)),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('type', 'Typed Answer')], max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.exam')),
            ],
        ),
    ]
