# Generated by Django 4.1.1 on 2022-09-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_exam_question_studentannouncement_teacherannouncement_testquestion_testquizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_category',
        ),
        migrations.AddField(
            model_name='class',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassCategory',
        ),
    ]
