# Generated by Django 4.1.2 on 2023-01-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0010_askquestion_askquestionanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "classes"},
        ),
    ]
