# Generated by Django 4.1.2 on 2023-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0011_alter_class_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="term",
            field=models.CharField(
                choices=[
                    ("Term 1", "Term 1"),
                    ("Term 2", "Term 2"),
                    ("Term 3", "Term 3"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcetextbook",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("Revision Materials", "Revision Materials"),
                    ("Textbooks", "Textbooks"),
                ],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcetextbook",
            name="revision_material_type",
            field=models.CharField(
                blank=True,
                choices=[("Exams", "Exams"), ("Revision Books", "Revision Books")],
                max_length=200,
                null=True,
            ),
        ),
    ]
